name: Code Climate Reporter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: actions/setup-go@v2


      with:
        go-version: '1.14.1'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Build
      run: go build .

    - name: Upload to code climate
      uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
      with:
        coverageCommand: go test -coverprofile c.out
